# Config for single device full finetuning in full_finetune_single_device.py
# using a Llama3.1 8B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Meta-Llama-3.1-8B-Instruct --output-dir /tmp/Meta-Llama-3.1-8B-Instruct --ignore-patterns "original/consolidated.00.pth"
#
# To launch on a single device, run the following command from root:
#   tune run full_finetune_single_device --config llama3_1/8B_full_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run full_finetune_single_device --config llama3_1/8B_full_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /home/aac/Llama3_1-8B-Instruct/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  source: /home/aac/TrainData
  train_on_input: False
seed: null
# shuffle: True
shuffle: False

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /home/aac/Llama3_1-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /home/aac/Llama3_1-8B-Instruct/checkpoints
  model_type: LLAMA3
  safe_serialization: True
resume_from_checkpoint: False


# Fine-tuning arguments
# batch_size: 2
batch_size: 1
epochs: 5
optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1
optimizer_in_bwd: True
compile: False

# Training environment
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  # _component_: torchtune.utils.metric_logging.DiskLogger
  _component_: torchtune.utils.metric_logging.WandBLogger
  log_dir: ${output_dir}
  project: torchtune-full
  group: llama3_1-8B-full-finetunning
output_dir: /home/aac/Llama3_1-8B-Instruct/logs
log_every_n_steps: 1
log_peak_memory_stats: False

